### ISSUE TITLE
Не стоит определять функции внутри функций. Вынеси функцию за пределы функции main

### ISSUE THREAD

**Issue by DanaZL** [Vixroff/learn-homework-1#1]
https://github.com/Vixroff/learn-homework-1/blob/1b1b4944d4f685a1e3f78909cf4a591d84c8b165/1_if1.py#L19

**Comment by Vixroff** [comment]
А имеет значение, будет ли она выше или ниже функции main?

**Comment by DanaZL** [comment]
Мы вызываем функции внутри main, так что надо определить выше
